version: 2.1

orbs:
  codecov: codecov/codecov@1
  snyk: snyk/snyk@0.0.10

executors:
  java:
    docker:
      - image: cimg/openjdk:11.0
    environment:
      JVM_OPTS: -Xmx2g
      TERM: dumb
  gradle_machine:
    machine:
      image: ubuntu-1604:201903-01
    environment:
      JVM_OPTS: -Xmx2g
      TERM: dumb

commands:
  gradle:
    description: 'Run the provided gradle command'
    parameters:
      args:
        type: string
      when:
        default: "on_success"
        type: enum
        enum: ["on_fail", "on_success", "always"]
    steps:
      - run:
          name: << parameters.args >>
          command: ./gradlew << parameters.args >> --info --max-workers=2 --continue
          when: << parameters.when >>
  setup_build_environment:
    description: 'Generates cache key from a hash of all gradle files'
    steps:
      - checkout
      - run:
          name: Generate cache key
          command: find . -type f -name "*.gradle*" -o -name "gradle-wrapper*" -exec shasum {} + | sort > /tmp/checksum.txt && cat /tmp/checksum.txt
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "/tmp/checksum.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
  populate_and_save_cache:
    description: 'Downloads all gradle dependencies and uploads cache for later use'
    steps:
      - gradle:
          args: downloadDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "/tmp/checksum.txt" }}
  machine_install_java11:
    description: "Install java11 on machine executor"
    steps:
      - run:
          name: Install open jdk11
          command: |
            sudo apt-get update
            sudo apt-get install openjdk-11-jdk
            sudo sh -c 'for bin in /usr/lib/jvm/java-11-openjdk-amd64/bin/*; do update-alternatives --install /usr/bin/$(basename $bin) $(basename $bin) $bin 100; done'
            sudo sh -c 'for bin in /usr/lib/jvm/java-11-openjdk-amd64/bin/*; do update-alternatives --set $(basename $bin) $bin; done'

jobs:
  build:
    executor: java
    steps:
      - setup_build_environment
      - populate_and_save_cache
      - gradle:
          args: build
      - gradle:
          args: jacocoTestReport
      - codecov/upload:
          flags: unit
  integration-test:
    executor: gradle_machine
    steps:
      - machine_install_java11
      - setup_build_environment
      - populate_and_save_cache
      - gradle:
          args: jacocoIntegrationTestReport
      - codecov/upload:
          flags: integration
  publish:
    executor: java
    steps:
      - setup_build_environment
      - gradle:
          args: :tag -Prelease
      - gradle:
          args: publish
      - add_ssh_keys:
          fingerprints:
            - '9b:14:3f:fc:8e:d6:08:c7:a7:2b:57:c4:6e:32:73:58'
      - run: git push origin $(./gradlew -q :printVersion)
  snyk-scan:
    executor:
      name: java
    environment:
      GRADLE_OPTS: -Dorg.gradle.workers.max=1 # Snyk doesn't handle parallelism well
    steps:
      - setup_build_environment
      - snyk/scan:
          additional-arguments: --all-sub-projects

workflows:
  version: 2
  build-and-publish:
    jobs:
      - build
      - integration-test
      - snyk-scan:
          context: hypertrace-vulnerability-scanning
      - publish:
          context: hypertrace-publishing
          requires:
            - build
            - integration-test
            - snyk-scan
          filters:
            branches:
              only:
                - main